---
title: "Fairfax Data Transformation"
author: "Allison O'Connor"
date: "October 16, 2014"
output: html_document
---


Here are the programming steps done in R to import and clean the data from Fairfax County Department of Tax Administration.
```{r}
layout <- read.csv("PDLayout.csv", stringsAsFactors = FALSE)
library(dplyr)
library(mullenMisc)
layout <- layout %>%
filter(!is.na (LENGTH))

```

```{r}
PDDataA <- read.fwf("cleanedFFXDataAA.txt", widths = layout$LENGTH, col.names = layout$COLUMN.NAME,
                    stringsAsFactors = FALSE)
PDDataB <- read.fwf("cleanedFFXDataAB.txt", widths = layout$LENGTH, col.names = layout$COLUMN.NAME,  stringsAsFactors = FALSE)
PDDataC <- read.fwf("cleanedFFXDataAC.txt", widths = layout$LENGTH, col.names = layout$COLUMN.NAME,  stringsAsFactors = FALSE)
PDDataD <- read.fwf("cleanedFFXDataAD.txt", widths = layout$LENGTH, col.names = layout$COLUMN.NAME,  stringsAsFactors = FALSE)
PDDataE <- read.fwf("cleanedFFXDataAE.txt", widths = layout$LENGTH, col.names = layout$COLUMN.NAME,  stringsAsFactors = FALSE)
PDDataF <- read.fwf("cleanedFFXDataAF.txt", widths = layout$LENGTH, col.names = layout$COLUMN.NAME,  stringsAsFactors = FALSE)
PDDataG <- read.fwf("cleanedFFXDataAG.txt", widths = layout$LENGTH, col.names = layout$COLUMN.NAME,  stringsAsFactors = FALSE)
PDDataH <- read.fwf("cleanedFFXDataAH.txt", widths = layout$LENGTH, col.names = layout$COLUMN.NAME,  stringsAsFactors = FALSE)

# take all the data pieces and bind them into one object, then remove all the little objects to free up memory.
 
FFXdata <- rbind(PDDataA, PDDataB, PDDataC, PDDataD, PDDataE, PDDataF, PDDataG, PDDataH)
rm(PDDataA, PDDataB, PDDataC, PDDataD, PDDataE, PDDataF, PDDataG, PDDataH)

```

Remove any non-residential records.

```{r}
# these are the codes for various residential land uses, which I will need further down. 
residential_codes <- c(011, 012, 013, 014, 015, 021, 029, 031, 032, 033, 034, 035, 036, 037, 039, 040, 041, 042, 043, 044, 045, 046, 047, 048, 049)

FFX_res_data <- FFXdata %>%
 filter(LUC%in% residential_codes) %>%
 select(parcel_id = PARID,
        address_number = ADRNO,
        address_number_suffix = ADRADD,
        street_direction = ADRDIR,
        street_name = ADRSTR,
        street_suffix = ADRSUF,
        city_name = CITYNAME,
        zip = ZIP1,
        sale_price = PRICE,
        sale_date = SALEDT,
        fireplaces = WBFP_O...WBFP_PF,
        year_built = YRBLT,
        land_use_code = LUC,
        sqft_living_area = SFLA) %>%
  mutate(decade = round_year(year_built, round_to = "decade")) %>%
  mutate(fireplaces = as.integer(fireplaces)) %>%
  filter(year_built < 2100) %>%
  tbl_df()
```

Start playing around with data plots.
```{r}
library(ggplot2)

ggplot(data = FFX_res_data,
       aes(x = decade, y = fireplaces))+
  
  

```

Look for weird data.

```{r}
lots_o_fireplaces <- FFX_res_data %>%
  filter(fireplaces > 6)
View(lots_o_fireplaces)  
```